apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /giropops
      name: giropops-volume
  volumes:
  - name: giropops-volume
    persistentVolumeClaim:
      claimName: giropops-pvc