apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "1.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
